random_forest:
  'init':
    'random_state': 42
  'grid':
    'params':
      'n_estimators': [200, 500]
      'max_features': ['auto', 'sqrt']
      'max_depth': [4,5,100]
      'criterion': ['gini', 'entropy']
    'cv': 5
logistic_regression:
  'no_parms': None